services:
  ts-fontend-simple-n1:
    labels:
      shipyard.primary-route: true
      shipyard.route: '/'
    image: ts-frontend-simple-img-n1
    build:
      context: ./ts-frontend
      dockerfile: Dockerfile.3
    init: true
    networks:
      - app_network
    ports:
      - 5173:8027

networks:
  app_network:
