services:
  ts-fontend-simple-n1:
    labels:
      shipyard.primary-route: true
      shipyard.route: '/'
    image: ts-frontend-simple-img-n1
    build:
      context: ./ts_frontend
      dockerfile: Dockerfile.3
    init: true
    volumes:
      - type: bind
        source: ./ts-frontend/
        target: /usr/src/app/
      - .:/workspace:cached
      # Avoids bringing node modules into the container
      - type: volume
        target: /usr/src/app/node_modules
      # No need because above all sources from withing ts-frontend was already targeted into /usr/src/app/
      # using just for in case
      - type: bind
        source: ./ts-frontend/webpack.devserver.conf.js
        target: /usr/src/app/webpack.devserver.conf.js
    networks:
      - app_network
    ports:
      - 5173:8027

networks:
  app_network:
