name: image-ci

on:
  push:
    branches:
      - 'github-action'
    tags:
      - 'v*'
jobs:
  build-tag-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3